export enum FrameworkEvents {
    Done = "ajaxDone",
    Always = "ajaxAlways",
    Fail = "ajaxFail",
    ConfirmMessage = "ajaxConfirmMessage",
    Complete = "ajaxComplete",
    ErrorMessage = "ajaxErrorMessage",
    Error = "ajaxError",
    Success = "ajaxSuccess",
    InvalidField = "ajaxInvalidField",
    UpdateComplete = 'ajaxUpdateComplete',
    BeforeRequest = 'oc.beforeRequest',
    BeforeUpdate = 'ajaxBeforeUpdate',
    Update = 'ajaxUpdate',
    BeforeReplace = 'ajaxBeforeReplace',
    Validation = 'ajaxValidation',
    Promise = 'ajaxPromise',
    BeforeSend = 'ajaxBeforeSend',
}
